"""Init tables

Revision ID: 21fb6efb7ecb
Revises: 
Create Date: 2019-09-01 23:09:22.010153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fb6efb7ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('co2', sa.Integer(), nullable=True),
    sa.Column('hum', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_timestamp'), 'records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_timestamp'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
